# Generated by Django 5.2.17 on 2026-09-22 19:56

import django.db.models.deletion
import sova.reports.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('interactions', 'Взаимодействия с вузами')], default='interactions', max_length=32, verbose_name='Тип отчёта')),
                ('spec', models.JSONField(verbose_name='Параметры отчёта')),
                ('format', models.CharField(choices=[('xlsx', 'XLSX'), ('xls', 'XLS'), ('pdf', 'PDF'), ('json', 'JSON')], max_length=8, verbose_name='Формат')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Строится'), ('ready', 'Готов'), ('failed', 'Ошибка')], default='queued', max_length=16, verbose_name='Состояние')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Хранится до')),
                ('file', models.FileField(blank=True, max_length=500, storage=sova.reports.models.reports_storage, upload_to=sova.reports.models.report_upload_to, verbose_name='Файл')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Размер файла, байт')),
                ('rows_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Число строк')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток')),
                ('error_code', models.CharField(blank=True, max_length=64, verbose_name='Код ошибки')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='Сообщение об ошибке')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Задание на отчёт',
                'verbose_name_plural': 'Задания на отчёты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='report_job_owner_idx'), models.Index(fields=['status', 'expires_at'], name='report_job_status_idx')],
            },
        ),
    ]
