# Generated by Django 5.2.17 on 2026-09-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_organization_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportjob',
            name='report_type',
            field=models.CharField(choices=[('interactions', 'Взаимодействия с организациями')], default='interactions', max_length=32, verbose_name='Тип отчёта'),
        ),
    ]
