# Generated by Django 5.2.17 on 2026-09-20 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('b2c_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='catalog.b2cclient', verbose_name='B2C-клиент')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='catalog.university', verbose_name='Вуз')),
            ],
            options={
                'verbose_name': 'Взаимодействие',
                'verbose_name_plural': 'Взаимодействия',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='Файл договора')),
                ('contract_number', models.CharField(blank=True, max_length=255, verbose_name='Номер договора')),
                ('sent_at', models.DateField(blank=True, null=True, verbose_name='Отправлен на подписание')),
                ('corrected_at', models.DateField(blank=True, null=True, verbose_name='Скорректирован перед подписанием')),
                ('signed_at', models.DateField(blank=True, null=True, verbose_name='Подписан')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='interactions.interaction', verbose_name='Взаимодействие')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InteractionDirection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_directions', to='interactions.interaction', verbose_name='Взаимодействие')),
                ('it_direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interaction_directions', to='catalog.itdirection', verbose_name='ИТ-направление')),
            ],
            options={
                'verbose_name': 'Направление взаимодействия',
                'verbose_name_plural': 'Направления взаимодействия',
                'ordering': ['interaction', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='InteractionProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_programs', to='interactions.interaction', verbose_name='Взаимодействие')),
                ('it_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interaction_programs', to='catalog.itprogram', verbose_name='ИТ-программа')),
            ],
            options={
                'verbose_name': 'Программа взаимодействия',
                'verbose_name_plural': 'Программы взаимодействия',
                'ordering': ['interaction', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='InteractionProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_products', to='interactions.interaction', verbose_name='Взаимодействие')),
                ('it_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interaction_products', to='catalog.itproduct', verbose_name='ИТ-продукт')),
                ('interaction_program', models.ForeignKey(blank=True, help_text='Пусто — продукт добавлен вне привязки к программе.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interaction_products', to='interactions.interactionprogram', verbose_name='Программа взаимодействия')),
            ],
            options={
                'verbose_name': 'Продукт взаимодействия',
                'verbose_name_plural': 'Продукты взаимодействия',
                'ordering': ['interaction', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('signed_at', models.DateField(blank=True, null=True, verbose_name='Дата подписания лицензии')),
                ('superseded_at', models.DateTimeField(blank=True, null=True, verbose_name='Заменена')),
                ('valid_until_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Действует до (год)')),
                ('is_signed', models.BooleanField(default=False, verbose_name='Подписана')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующая')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='interactions.contract', verbose_name='Договор')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('interaction_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='interactions.interactionproduct', verbose_name='Продукт взаимодействия')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Назначен')),
                ('unassigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Снят с назначения')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsibles_as_assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='interactions.interaction', verbose_name='Взаимодействие')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsibles_as_manager', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
            ],
            options={
                'verbose_name': 'Ответственный',
                'verbose_name_plural': 'Ответственные',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('b2c_client__isnull', True), ('university__isnull', False)), models.Q(('b2c_client__isnull', False), ('university__isnull', True)), _connector='OR'), name='interaction_exactly_one_counterparty'),
        ),
        migrations.AddConstraint(
            model_name='interactiondirection',
            constraint=models.UniqueConstraint(fields=('interaction', 'it_direction'), name='unique_direction_per_interaction'),
        ),
        migrations.AddConstraint(
            model_name='interactionprogram',
            constraint=models.UniqueConstraint(fields=('interaction', 'it_program'), name='unique_program_per_interaction'),
        ),
        migrations.AddConstraint(
            model_name='interactionproduct',
            constraint=models.UniqueConstraint(fields=('interaction', 'it_product'), name='unique_product_per_interaction'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('contract', 'interaction_product'), name='one_active_license_per_contract_interaction_product'),
        ),
        migrations.AddConstraint(
            model_name='responsible',
            constraint=models.UniqueConstraint(condition=models.Q(('unassigned_at__isnull', True)), fields=('interaction',), name='one_active_responsible_per_interaction'),
        ),
    ]
