# Generated by Django 5.2.17 on 2026-09-20 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_direction_options_alter_product_options_and_more'),
        ('interactions', '0002_rename_catalog_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiondirection',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interaction_directions', to='catalog.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='interactionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interaction_products', to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='interactionprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interaction_programs', to='catalog.program', verbose_name='Программа'),
        ),
    ]
