# Generated by Django 5.2.17 on 2026-09-22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0005_alter_direction_options_alter_product_options_and_more"),
        ("interactions", "0003_alter_interactiondirection_direction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractionContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата привязки")),
                ("unlinked_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата отвязки")),
                (
                    "contact_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interaction_links",
                        to="catalog.contactperson",
                        verbose_name="Контактное лицо",
                    ),
                ),
                (
                    "interaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_links",
                        to="interactions.interaction",
                        verbose_name="Взаимодействие",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interaction_contact_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кем привязан",
                    ),
                ),
                (
                    "unlinked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interaction_contact_unlinks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кем отвязан",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт взаимодействия",
                "verbose_name_plural": "Контакты взаимодействий",
                "ordering": ["linked_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="interactioncontact",
            constraint=models.UniqueConstraint(
                condition=Q(unlinked_at__isnull=True),
                fields=("interaction", "contact_person"),
                name="unique_active_interaction_contact",
            ),
        ),
        migrations.AddIndex(
            model_name="interactioncontact",
            index=models.Index(
                fields=["interaction", "unlinked_at"],
                name="interaction_contact_active_idx",
            ),
        ),
    ]
