# Generated by Django 5.2.17 on 2026-09-23 11:00

import sova.core.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_interactioncontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Исходное имя файла договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=sova.core.files.uuid_upload_to('contracts'), verbose_name='Файл договора'),
        ),
    ]
