# Generated by Django 5.2.17 on 2026-09-23 11:10

import django.db.models.deletion
import sova.core.files
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_contract_backfill_file_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=sova.core.files.uuid_upload_to('contracts'), verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Исходное имя файла')),
                ('size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Размер файла, байт')),
                ('content_type', models.CharField(blank=True, max_length=255, verbose_name='MIME-тип')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='interactions.contract', verbose_name='Договор')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_files', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Файл договора',
                'verbose_name_plural': 'Файлы договора',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
