# Generated by Django 5.2.17 on 2026-09-24 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0008_contractfile_backfill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='responsible',
            name='one_active_responsible_per_interaction',
        ),
        migrations.AddConstraint(
            model_name='responsible',
            constraint=models.UniqueConstraint(condition=models.Q(('unassigned_at__isnull', True)), fields=('interaction', 'manager'), name='one_active_responsible_per_manager'),
        ),
    ]
