# Generated by Django 5.2.17 on 2026-09-22 17:00

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_counterparty(apps, schema_editor):
    """Копирует контрагента из Interaction в существующие договоры до появления constraint."""
    Contract = apps.get_model("interactions", "Contract")
    Interaction = apps.get_model("interactions", "Interaction")
    interaction = Interaction.objects.filter(pk=OuterRef("interaction_id"))
    Contract.objects.filter(university__isnull=True, b2c_client__isnull=True).update(
        university_id=Subquery(interaction.values("university_id")[:1]),
        b2c_client_id=Subquery(interaction.values("b2c_client_id")[:1]),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_direction_options_alter_product_options_and_more'),
        ('interactions', '0009_responsible_many_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='b2c_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='catalog.b2cclient', verbose_name='B2C-клиент'),
        ),
        migrations.AddField(
            model_name='contract',
            name='draft_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий (из файла)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='draft_manager_full_name',
            field=models.CharField(blank=True, help_text='Не резолвится в User на импорте — только на привязке договора к Interaction.', max_length=255, verbose_name='ФИО менеджера (из файла)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='draft_status',
            field=models.CharField(blank=True, help_text='Информационное поле, не влияет на WorkflowInstance/StageInstance.', max_length=255, verbose_name='Статус по передаче (из файла)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='catalog.university', verbose_name='Вуз'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='interactions.interaction', verbose_name='Взаимодействие'),
        ),
        migrations.RunPython(backfill_counterparty, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('b2c_client__isnull', True), ('university__isnull', False)), models.Q(('b2c_client__isnull', False), ('university__isnull', True)), _connector='OR'), name='contract_exactly_one_counterparty'),
        ),
    ]
