# Generated by Django 5.2.17 on 2026-09-22 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_direction_options_alter_product_options_and_more'),
        ('interactions', '0010_contract_headless'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='interactiondirection',
            name='unique_direction_per_interaction',
        ),
        migrations.RemoveConstraint(
            model_name='interactionproduct',
            name='unique_product_per_interaction',
        ),
        migrations.RemoveConstraint(
            model_name='interactionprogram',
            name='unique_program_per_interaction',
        ),
        migrations.AddField(
            model_name='interactiondirection',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Заполнен всегда, если запись пришла из импорта договора; interaction — только после привязки договора к взаимодействию.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_directions', to='interactions.contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='interactionproduct',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_products', to='interactions.contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='interactionprogram',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_programs', to='interactions.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='interactiondirection',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_directions', to='interactions.interaction', verbose_name='Взаимодействие'),
        ),
        migrations.AlterField(
            model_name='interactionproduct',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_products', to='interactions.interaction', verbose_name='Взаимодействие'),
        ),
        migrations.AlterField(
            model_name='interactionprogram',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_programs', to='interactions.interaction', verbose_name='Взаимодействие'),
        ),
        migrations.AddConstraint(
            model_name='interactiondirection',
            constraint=models.CheckConstraint(condition=models.Q(('interaction__isnull', False), ('contract__isnull', False), _connector='OR'), name='interaction_direction_has_owner'),
        ),
        migrations.AddConstraint(
            model_name='interactiondirection',
            constraint=models.UniqueConstraint(condition=models.Q(('interaction__isnull', False)), fields=('interaction', 'direction'), name='unique_direction_per_interaction'),
        ),
        migrations.AddConstraint(
            model_name='interactiondirection',
            constraint=models.UniqueConstraint(condition=models.Q(('contract__isnull', False)), fields=('contract', 'direction'), name='unique_direction_per_contract'),
        ),
        migrations.AddConstraint(
            model_name='interactionproduct',
            constraint=models.CheckConstraint(condition=models.Q(('interaction__isnull', False), ('contract__isnull', False), _connector='OR'), name='interaction_product_has_owner'),
        ),
        migrations.AddConstraint(
            model_name='interactionproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('interaction__isnull', False)), fields=('interaction', 'product'), name='unique_product_per_interaction'),
        ),
        migrations.AddConstraint(
            model_name='interactionproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('contract__isnull', False)), fields=('contract', 'product'), name='unique_product_per_contract'),
        ),
        migrations.AddConstraint(
            model_name='interactionprogram',
            constraint=models.CheckConstraint(condition=models.Q(('interaction__isnull', False), ('contract__isnull', False), _connector='OR'), name='interaction_program_has_owner'),
        ),
        migrations.AddConstraint(
            model_name='interactionprogram',
            constraint=models.UniqueConstraint(condition=models.Q(('interaction__isnull', False)), fields=('interaction', 'program'), name='unique_program_per_interaction'),
        ),
        migrations.AddConstraint(
            model_name='interactionprogram',
            constraint=models.UniqueConstraint(condition=models.Q(('contract__isnull', False)), fields=('contract', 'program'), name='unique_program_per_contract'),
        ),
    ]
