# Generated by Django 5.2.17 on 2026-09-24 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0012_normalize_contract_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='responsible',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Заполнен, если назначение пришло из реестра договоров; остаётся и после перехода на взаимодействие.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='interactions.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='interactions.interaction', verbose_name='Взаимодействие'),
        ),
        migrations.AddConstraint(
            model_name='responsible',
            constraint=models.CheckConstraint(condition=models.Q(('interaction__isnull', False), ('contract__isnull', False), _connector='OR'), name='responsible_has_owner'),
        ),
        migrations.AddConstraint(
            model_name='responsible',
            constraint=models.UniqueConstraint(condition=models.Q(('unassigned_at__isnull', True)), fields=('contract', 'manager'), name='one_active_responsible_per_contract'),
        ),
    ]
