# Generated by Django 5.2.17 on 2026-09-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0013_responsible_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='draft_manager_full_name',
        ),
    ]
