# Generated by Django 5.2.17 on 2026-09-26 15:09

import sova.core.files
import uuid
from django.db import migrations, models


def create_contract_template(apps, schema_editor):
    """Базовый шаблон договора: файл .docx загружается позже через админку."""
    DocumentTemplate = apps.get_model("interactions", "DocumentTemplate")
    DocumentTemplate.objects.get_or_create(kind="contract", defaults={"name": "Договор"})


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0014_remove_contract_draft_manager_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('kind', models.CharField(choices=[('contract', 'Договор')], max_length=50, verbose_name='Тип документа')),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to=sova.core.files.uuid_upload_to('document_templates'), verbose_name='Файл шаблона (.docx)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.RunPython(create_contract_template, migrations.RunPython.noop),
    ]
