# Generated by Django 5.2.17 on 2026-09-20 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name_snapshot', models.CharField(max_length=255, verbose_name='Название действия (слепок)')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='Плановое начало')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='Плановое окончание')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое начало')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое окончание')),
                ('execution_no', models.PositiveIntegerField(default=1, verbose_name='Номер исполнения')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_instances', to='workflows.workflowaction', verbose_name='Действие')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_instances', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Экземпляр действия',
                'verbose_name_plural': 'Экземпляры действий',
                'ordering': ['stage_instance', 'planned_start'],
            },
        ),
        migrations.CreateModel(
            name='ActionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='action_attachments/%Y/%m/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
                ('action_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_attachments', to='processes.actioninstance', verbose_name='Экземпляр действия')),
            ],
            options={
                'verbose_name': 'Вложение действия',
                'verbose_name_plural': 'Вложения действий',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_name_snapshot', models.CharField(max_length=255, verbose_name='Название исхода (слепок)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('action_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='processes.actioninstance', verbose_name='Экземпляр действия')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_results', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_results', to='workflows.actionoutcome', verbose_name='Исход')),
            ],
            options={
                'verbose_name': 'Результат действия',
                'verbose_name_plural': 'Результаты действий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(choices=[('interaction', 'Взаимодействие целиком'), ('it_direction', 'ИТ-направление'), ('it_program', 'ИТ-программа'), ('it_product', 'ИТ-продукт')], default='interaction', max_length=20, verbose_name='Тип контекста')),
                ('context_id', models.UUIDField(blank=True, help_text='Указывает на Interaction.id, InteractionDirection.id, InteractionProgram.id или InteractionProduct.id — по значению context_type.', null=True, verbose_name='ID контекста')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_instances', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_instances', to='workflows.workflowstage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Экземпляр этапа',
                'verbose_name_plural': 'Экземпляры этапов',
                'ordering': ['workflow_instance', 'added_at'],
            },
        ),
        migrations.AddField(
            model_name='actioninstance',
            name='stage_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_instances', to='processes.stageinstance', verbose_name='Экземпляр этапа'),
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начат')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_instances', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='interactions.interaction', verbose_name='Взаимодействие')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances', to='workflows.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Процесс workflow',
                'verbose_name_plural': 'Процессы workflow',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='stageinstance',
            name='workflow_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_instances', to='processes.workflowinstance', verbose_name='Процесс workflow'),
        ),
    ]
