# Generated by Django 5.2.17 on 2026-09-20 16:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('processes', '0001_initial'),
        ('workflows', '0003_stage_transition_and_action_start_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageRollback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('mode', models.CharField(choices=[('restart', 'Заново'), ('last_only', 'Только последнее обязательное действие')], help_text='Как возвращается этап, на который вернулся процесс: заново целиком или только последнее обязательное действие.', max_length=20, verbose_name='Режим')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Откат этапа',
                'verbose_name_plural': 'Откаты этапов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stageinstance',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Момент, когда этап стал доступен; отличается от момента создания экземпляра (added_at).', null=True, verbose_name='Открыт'),
        ),
        migrations.AlterField(
            model_name='actioninstance',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Завершено')], default='pending', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='stageinstance',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Завершён')], default='pending', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='status',
            field=models.CharField(choices=[('running', 'Идёт'), ('completed', 'Завершён')], default='running', max_length=50, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='stageinstance',
            index=models.Index(fields=['context_type', 'context_id'], name='stage_instance_context_idx'),
        ),
        migrations.AddConstraint(
            model_name='actioninstance',
            constraint=models.UniqueConstraint(fields=('stage_instance', 'action', 'execution_no'), name='unique_action_execution'),
        ),
        migrations.AddConstraint(
            model_name='stageinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('context_id__isnull', False)), fields=('workflow_instance', 'stage', 'context_type', 'context_id'), name='unique_stage_instance_per_context'),
        ),
        migrations.AddConstraint(
            model_name='stageinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('context_id__isnull', True)), fields=('workflow_instance', 'stage', 'context_type'), name='unique_stage_instance_without_context'),
        ),
        migrations.AddConstraint(
            model_name='workflowinstance',
            constraint=models.UniqueConstraint(fields=('workflow', 'interaction'), name='unique_workflow_per_interaction'),
        ),
        migrations.AddField(
            model_name='stagerollback',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_rollbacks', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='stagerollback',
            name='from_stage_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollbacks_as_cancelled', to='processes.stageinstance', verbose_name='Отменённый этап'),
        ),
        migrations.AddField(
            model_name='stagerollback',
            name='to_stage_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollbacks_as_target', to='processes.stageinstance', verbose_name='Этап возврата'),
        ),
        migrations.AddField(
            model_name='stagerollback',
            name='workflow_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_rollbacks', to='processes.workflowinstance', verbose_name='Процесс workflow'),
        ),
    ]
