# Generated by Django 5.2.17 on 2026-09-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_statuses_constraints_and_stage_rollback'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioninstance',
            name='triggered_at',
            field=models.DateTimeField(blank=True, help_text='Момент запуска переходом по исходу другого действия. Отличает запущенное, но ждущее зависимостей действие от ещё не запущенного.', null=True, verbose_name='Запущено переходом'),
        ),
    ]
