# Generated by Django 5.2.17 on 2026-09-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_actioninstance_triggered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageinstance',
            name='context_type',
            field=models.CharField(choices=[('interaction', 'Взаимодействие целиком'), ('direction', 'ИТ-направление'), ('program', 'ИТ-программа'), ('product', 'ИТ-продукт')], default='interaction', max_length=20, verbose_name='Тип контекста'),
        ),
    ]
