# Generated by Django 5.2.17 on 2026-09-21 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_alter_stageinstance_context_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRollback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_rollbacks', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('from_action_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollbacks_as_cancelled', to='processes.actioninstance', verbose_name='Отменённое исполнение')),
                ('stage_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_rollbacks', to='processes.stageinstance', verbose_name='Экземпляр этапа')),
                ('to_action_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollbacks_as_target', to='processes.actioninstance', verbose_name='Новое исполнение')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_rollbacks', to='processes.workflowinstance', verbose_name='Процесс workflow')),
            ],
            options={
                'verbose_name': 'Откат действия',
                'verbose_name_plural': 'Откаты действий',
                'ordering': ['-created_at'],
            },
        ),
    ]
