# Generated by Django 5.2.17 on 2026-09-22 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_actionrollback'),
        ('workflows', '0008_actionfeature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionFeatureExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_code_snapshot', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.UUIDField()),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('action_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_executions', to='processes.actioninstance')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='workflows.actionfeature')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_feature_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['performed_at'],
            },
        ),
    ]
