# Generated by Django 5.2.17 on 2026-09-23 11:00

import sova.core.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0007_actionfeatureexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionattachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='MIME-тип'),
        ),
        migrations.AddField(
            model_name='actionattachment',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Исходное имя файла'),
        ),
        migrations.AddField(
            model_name='actionattachment',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Размер файла, байт'),
        ),
        migrations.AlterField(
            model_name='actionattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to=sova.core.files.uuid_upload_to('action_attachments'), verbose_name='Файл'),
        ),
    ]
