# Generated by Django 5.2.17 on 2026-09-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('direct', 'Личная переписка'), ('system', 'Системные сообщения')], max_length=16, verbose_name='Тип беседы'),
        ),
    ]
