# Generated by Django 5.2.17 on 2026-09-26 06:55

import django.db.models.deletion
import sova.core.files
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_conversation_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.FileField(max_length=500, upload_to=sova.core.files.uuid_upload_to('message_attachments'), verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('size', models.PositiveBigIntegerField(verbose_name='Размер файла, байт')),
                ('content_type', models.CharField(max_length=255, verbose_name='MIME-тип')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message', verbose_name='Сообщение')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Вложение сообщения',
                'verbose_name_plural': 'Вложения сообщений',
                'indexes': [models.Index(fields=['uploaded_by', 'message', 'created_at'], name='msg_attach_owner_pending_idx')],
            },
        ),
    ]
