# Generated by Django 5.2.17 on 2026-09-26 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0009_responsible_many_active'),
        ('messaging', '0003_messageattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='interaction',
            field=models.OneToOneField(blank=True, help_text='Заполнено только у чата типа interaction; удаление Взаимодействия удаляет и чат.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='interactions.interaction', verbose_name='Взаимодействие'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='dedupe_key',
            field=models.CharField(help_text='Например, direct:<id1>:<id2>, system:<user_id> или interaction:<interaction_id>.', max_length=128, unique=True, verbose_name='Ключ дедупликации'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('direct', 'Личная переписка'), ('system', 'Системные сообщения'), ('interaction', 'Чат взаимодействия')], max_length=16, verbose_name='Тип беседы'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('interaction__isnull', False), ('kind', 'interaction')), models.Q(models.Q(('kind', 'interaction'), _negated=True), ('interaction__isnull', True)), _connector='OR'), name='interaction_conversation_requires_interaction'),
        ),
    ]
