# Generated by Django 5.2.17 on 2026-09-21 21:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Если не указан — используется email пользователя.', max_length=254, verbose_name='Email для уведомлений')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64, verbose_name='Telegram chat ID')),
                ('max_chat_id', models.CharField(blank=True, max_length=64, verbose_name='MAX chat ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль уведомлений',
                'verbose_name_plural': 'Профили уведомлений',
                'ordering': ['user_id'],
            },
        ),
    ]
