# Generated by Django 5.2.17 on 2026-09-23 19:21

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_type', models.CharField(choices=[('action_deadline', 'Сроки действия'), ('stage_deadline', 'Сроки этапа'), ('workflow_deadline', 'Сроки процесса'), ('kam_assigned', 'Назначение КАМа')], max_length=20, unique=True, verbose_name='Тип уведомления')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включено')),
                ('is_notify_responsible', models.BooleanField(default=True, verbose_name='Ответственному')),
                ('is_notify_head', models.BooleanField(default=False, verbose_name='Руководителю')),
                ('head_mode', models.CharField(choices=[('assigned_by', 'Назначивший руководитель'), ('all_heads', 'Все руководители')], default='assigned_by', help_text='«Назначивший руководитель» — тот, кто назначил КАМа на взаимодействие, если у него роль «Руководитель»; иначе — все руководители. Только для сроков: в событийных уведомлениях руководителя передаёт код события.', max_length=20, verbose_name='Руководитель')),
                ('is_fallback_to_head', models.BooleanField(default=True, help_text='Только для сроков: если получатель «ответственный» выбран, но ответственного нет.', verbose_name='Нет ответственного — руководителю')),
                ('remind_before_days', models.PositiveIntegerField(blank=True, help_text='Только для сроков. Пусто — не предупреждать.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Предупреждать за, дней')),
                ('is_remind_responsible', models.BooleanField(default=True, help_text='Только для сроков.', verbose_name='Предупреждение — ответственному')),
                ('is_remind_head', models.BooleanField(default=False, help_text='Только для сроков.', verbose_name='Предупреждение — руководителю')),
                ('is_channel_email', models.BooleanField(default=True, verbose_name='Email')),
                ('is_channel_telegram', models.BooleanField(default=True, verbose_name='Telegram')),
                ('is_channel_max', models.BooleanField(default=True, verbose_name='MAX')),
                ('delivery_mode', models.CharField(choices=[('digest', 'Сводкой'), ('separate', 'Отдельными сообщениями')], default='digest', help_text='Только для сроков.', max_length=20, verbose_name='Доставка')),
                ('repeat_every_days', models.PositiveIntegerField(blank=True, help_text='Только для сроков. Пусто — сообщить один раз.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Повторять о просрочке раз в, дней')),
                ('is_skip_weekends', models.BooleanField(default=False, help_text='Только для сроков.', verbose_name='Не отправлять в выходные')),
            ],
            options={
                'verbose_name': 'Настройки уведомления',
                'verbose_name_plural': 'Настройки уведомлений',
                'ordering': ['notify_type'],
            },
        ),
    ]
