# Generated by Django 5.2.17 on 2026-09-23 19:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notifysettings_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_type', models.CharField(choices=[('action_deadline', 'Сроки действия'), ('stage_deadline', 'Сроки этапа'), ('workflow_deadline', 'Сроки процесса')], max_length=20, verbose_name='Тип уведомления')),
                ('event', models.CharField(choices=[('overdue', 'Просрочка'), ('reminder', 'Предупреждение')], max_length=20, verbose_name='Событие')),
                ('object_id', models.UUIDField(help_text='ActionInstance, StageInstance или WorkflowInstance — по виду контроля.', verbose_name='ID объекта')),
                ('deadline', models.DateTimeField(verbose_name='Срок')),
                ('last_sent_at', models.DateTimeField(verbose_name='Последняя отправка')),
                ('send_count', models.PositiveIntegerField(default=1, verbose_name='Отправлено раз')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление о сроке',
                'verbose_name_plural': 'Журнал уведомлений о сроках',
                'ordering': ['-last_sent_at'],
                'indexes': [models.Index(fields=['object_id'], name='deadline_delivery_object')],
                'constraints': [models.UniqueConstraint(fields=('notify_type', 'event', 'object_id', 'deadline', 'recipient'), name='unique_deadline_delivery')],
            },
        ),
    ]
