# Generated by Django 5.2.17 on 2026-09-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_system_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifysettings",
            name="head_mode",
            field=models.CharField(choices=[("assigned_by", "Назначивший руководитель"), ("all_heads", "Все руководители"), ("supervisor", "Руководитель КАМа")], default="assigned_by", help_text="«Назначивший руководитель» — тот, кто назначил КАМа на взаимодействие, если у него роль «Руководитель»; «Руководитель КАМа» — руководители действующих КАМов взаимодействия. Если таких нет — все руководители. Только для сроков: в событийных уведомлениях руководителя передаёт код события.", max_length=20, verbose_name="Руководитель"),
        ),
        migrations.AlterField(
            model_name="notifysettings",
            name="notify_type",
            field=models.CharField(choices=[("action_deadline", "Сроки действия"), ("stage_deadline", "Сроки этапа"), ("workflow_deadline", "Сроки процесса"), ("kam_assigned", "Назначение КАМа"), ("head_assigned", "Назначение руководителя"), ("head_unassigned", "Снятие руководителя")], max_length=20, unique=True, verbose_name="Тип уведомления"),
        ),
    ]
