# Generated by Django 5.2.17 on 2026-09-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_head_notify_settings_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifysettings',
            name='notify_type',
            field=models.CharField(choices=[('action_deadline', 'Сроки действия'), ('stage_deadline', 'Сроки этапа'), ('workflow_deadline', 'Сроки процесса'), ('kam_assigned', 'Назначение КАМа'), ('head_assigned', 'Назначение руководителя'), ('head_unassigned', 'Снятие руководителя'), ('contact_unlinked', 'Отвязка контактного лица')], max_length=20, unique=True, verbose_name='Тип уведомления'),
        ),
    ]
