# Generated by Django 5.2.17 on 2026-09-27 11:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_contact_unlinked_notify_settings_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('expires_at', models.DateTimeField(verbose_name='Действителен до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
            ],
            options={
                'verbose_name': 'Токен привязки Telegram',
                'verbose_name_plural': 'Токены привязки Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_chat_id', ''), _negated=True), fields=('telegram_chat_id',), name='unique_non_empty_telegram_chat_id'),
        ),
        migrations.AddField(
            model_name='telegramlinktoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
