# Generated by Django 5.2.17 on 2026-09-24 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_user_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supervision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("head", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="supervised", to=settings.AUTH_USER_MODEL, verbose_name="Руководитель")),
                ("kam", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="supervision", to=settings.AUTH_USER_MODEL, verbose_name="КАМ")),
            ],
            options={
                "verbose_name": "руководитель КАМа",
                "verbose_name_plural": "руководители КАМов",
            },
        ),
    ]
