# Generated by Django 5.2.17 on 2026-09-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_supervision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('observer', 'Наблюдатель'), ('kam', 'КАМ'), ('head', 'Руководитель'), ('platform_admin', 'Администратор платформы')], max_length=32, verbose_name='Роль в системе'),
        ),
    ]
