# Generated by Django 5.2.17 on 2026-09-20 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('code', models.CharField(max_length=100, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('comment_required', models.BooleanField(default=False, verbose_name='Требует комментарий')),
                ('attachment_required', models.BooleanField(default=False, verbose_name='Требует вложение')),
            ],
            options={
                'verbose_name': 'Исход действия',
                'verbose_name_plural': 'Исходы действий',
                'ordering': ['action', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('default_duration_days', models.PositiveIntegerField(blank=True, help_text='Используется и как план (planned_end = planned_start + default_duration_days), и как порог контроля зависания действия. NULL — контроль зависания не ведётся.', null=True, verbose_name='Плановая длительность, дней')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Можно пропустить без исхода')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Действие workflow',
                'verbose_name_plural': 'Действия workflow',
                'ordering': ['stage', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Код')),
                ('audience', models.CharField(choices=[('b2b', 'Вузы'), ('b2c', 'Физ/юрлица')], default='b2b', max_length=10, verbose_name='Аудитория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('stale_threshold_days', models.PositiveIntegerField(blank=True, help_text='Считается от WorkflowInstance.started_at — сколько существует вся заявка. NULL — контроль зависания заявки целиком не ведётся.', null=True, verbose_name='SLA по заявке целиком, дней')),
                ('is_base', models.BooleanField(default=False, verbose_name='Базовый workflow')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflow',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActionTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transition', to='workflows.actionoutcome', verbose_name='Исход')),
                ('target_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_transitions', to='workflows.workflowaction', verbose_name='Целевое действие')),
            ],
            options={
                'verbose_name': 'Переход действия',
                'verbose_name_plural': 'Переходы действий',
                'ordering': ['outcome'],
            },
        ),
        migrations.AddField(
            model_name='actionoutcome',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_outcomes', to='workflows.workflowaction', verbose_name='Действие'),
        ),
        migrations.CreateModel(
            name='ActionDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_dependencies_as_action', to='workflows.workflowaction', verbose_name='Действие')),
                ('depends_on_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_dependencies_as_depends_on_action', to='workflows.workflowaction', verbose_name='Зависит от действия')),
            ],
            options={
                'verbose_name': 'Зависимость действия',
                'verbose_name_plural': 'Зависимости действий',
                'ordering': ['action', 'depends_on_action'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=50, verbose_name='Тип изменения')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Тип сущности')),
                ('entity_id', models.UUIDField(verbose_name='ID сущности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_changes', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_changes', to='workflows.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Изменение workflow',
                'verbose_name_plural': 'Изменения workflow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('is_initial', models.BooleanField(default=False, verbose_name='Начальный этап')),
                ('is_final', models.BooleanField(default=False, verbose_name='Финальный этап')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Можно пропустить')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_stages', to='workflows.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Этап workflow',
                'verbose_name_plural': 'Этапы workflow',
                'ordering': ['workflow', 'sort_order'],
            },
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_actions', to='workflows.workflowstage', verbose_name='Этап'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_base', True)), fields=('audience',), name='one_base_workflow_per_audience'),
        ),
        migrations.AddConstraint(
            model_name='actionoutcome',
            constraint=models.UniqueConstraint(fields=('action', 'code'), name='unique_action_outcome_code'),
        ),
        migrations.AddConstraint(
            model_name='actiondependency',
            constraint=models.UniqueConstraint(fields=('action', 'depends_on_action'), name='unique_action_dependency'),
        ),
        migrations.AddConstraint(
            model_name='actiondependency',
            constraint=models.CheckConstraint(condition=models.Q(('action', models.F('depends_on_action')), _negated=True), name='action_dependency_no_self_reference'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(fields=('workflow', 'sort_order'), name='unique_workflow_stage_order'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_initial', True)), fields=('workflow',), name='one_initial_stage_per_workflow'),
        ),
        migrations.AddConstraint(
            model_name='workflowaction',
            constraint=models.UniqueConstraint(fields=('stage', 'sort_order'), name='unique_stage_action_order'),
        ),
    ]
