# Generated by Django 5.2.17 on 2026-09-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstage',
            name='type',
            field=models.CharField(choices=[('interaction', 'Взаимодействие целиком'), ('it_direction', 'ИТ-направление'), ('it_program', 'ИТ-программа'), ('it_product', 'ИТ-продукт')], default='interaction', help_text='К чему относится этап: ко всему взаимодействию или к каждому его направлению, программе, продукту. Для каждого объекта соответствующего типа создаётся свой экземпляр этапа.', max_length=20, verbose_name='Тип этапа'),
        ),
    ]
