# Generated by Django 5.2.17 on 2026-09-20 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowstage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowaction',
            name='starts_by_transition_only',
            field=models.BooleanField(default=False, help_text='Действие не стартует при открытии этапа, а запускается переходом по исходу другого действия. Пока не запущено, не мешает закрытию этапа.', verbose_name='Запускается только переходом'),
        ),
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('from_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_transitions_as_from_stage', to='workflows.workflowstage', verbose_name='Этап-источник')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_transitions_as_to_stage', to='workflows.workflowstage', verbose_name='Этап-цель')),
            ],
            options={
                'verbose_name': 'Связь этапов',
                'verbose_name_plural': 'Связи этапов',
                'ordering': ['from_stage', 'to_stage'],
                'constraints': [models.UniqueConstraint(fields=('from_stage', 'to_stage'), name='unique_stage_transition'), models.CheckConstraint(condition=models.Q(('from_stage', models.F('to_stage')), _negated=True), name='stage_transition_no_self_reference')],
            },
        ),
    ]
