# Generated by Django 5.2.17 on 2026-09-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_alter_workflowstage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstage',
            name='type',
            field=models.CharField(choices=[('interaction', 'Взаимодействие целиком'), ('direction', 'Направление'), ('program', 'Программа'), ('product', 'Продукт')], default='interaction', help_text='К чему относится этап: ко всему взаимодействию или к каждому его направлению, программе, продукту. Для каждого объекта соответствующего типа создаётся свой экземпляр этапа.', max_length=20, verbose_name='Тип этапа'),
        ),
    ]
