# Generated by Django 5.2.17 on 2026-09-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_alter_workflowstage_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actiondependency',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='actionoutcome',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='actiontransition',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='stagetransition',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='workflowaction',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='workflowstage',
            old_name='active',
            new_name='is_active',
        ),
    ]
