# Generated by Django 5.2.17 on 2026-09-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_rename_active_to_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionoutcome',
            old_name='attachment_required',
            new_name='is_attachment_required',
        ),
        migrations.RenameField(
            model_name='actionoutcome',
            old_name='comment_required',
            new_name='is_comment_required',
        ),
        migrations.RenameField(
            model_name='workflowaction',
            old_name='starts_by_transition_only',
            new_name='is_trigger_only',
        ),
    ]
