# Generated by Django 5.2.17 on 2026-09-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_alter_workflowstage_type'),
        ('workflows', '0006_rename_required_and_trigger_only_fields'),
    ]

    operations = [
    ]
