# Generated by Django 5.2.17 on 2026-09-22 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_merge_20260921_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('code', models.CharField(choices=[('contact_person.create', 'Создать контакт'), ('contact_person.select', 'Выбрать контакт'), ('contract.create', 'Создать договор'), ('contract.update', 'Изменить договор'), ('contract.sign', 'Подписать договор'), ('contract.file.upload', 'Загрузить файл договора'), ('license.create', 'Создать лицензию'), ('license.update', 'Изменить лицензию'), ('communication.create', 'Создать коммуникацию'), ('meeting.create', 'Создать встречу'), ('installation.create', 'Создать установку'), ('training.create', 'Создать обучение'), ('program_update.create', 'Создать обновление программы'), ('result_check.create', 'Создать проверку результата')], max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='workflows.workflowaction')),
            ],
            options={
                'ordering': ['sort_order'],
                'constraints': [models.UniqueConstraint(fields=('action', 'code'), name='unique_action_feature_code'), models.UniqueConstraint(fields=('action', 'sort_order'), name='unique_action_feature_order')],
            },
        ),
    ]
