# Generated by Django 5.2.17 on 2026-09-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_actionfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionfeature',
            name='code',
            field=models.CharField(choices=[('contact_person.create', 'Создать контакт'), ('contact_person.select', 'Выбрать контакт'), ('contact_person.update', 'Изменить контакт'), ('contact_person.deactivate', 'Деактивировать контакт'), ('responsible.assign', 'Назначить ответственного'), ('responsible.unassign', 'Снять ответственного'), ('interaction_direction.add', 'Добавить направление'), ('interaction_direction.remove', 'Убрать направление'), ('interaction_program.add', 'Добавить программу'), ('interaction_program.remove', 'Убрать программу'), ('interaction_product.add', 'Добавить продукт'), ('interaction_product.remove', 'Убрать продукт'), ('contract.create', 'Создать договор'), ('contract.update', 'Изменить договор'), ('contract.sign', 'Подписать договор'), ('contract.file.upload', 'Загрузить файл договора'), ('contract.mark_sent', 'Отметить отправку договора'), ('contract.mark_corrected', 'Отметить доработку договора'), ('license.create', 'Создать лицензию'), ('license.update', 'Изменить лицензию'), ('communication.create', 'Создать коммуникацию'), ('meeting.create', 'Создать встречу'), ('installation.create', 'Создать установку'), ('training.create', 'Создать обучение'), ('program_update.create', 'Создать обновление программы'), ('result_check.create', 'Создать проверку результата'), ('checklist.fill', 'Заполнить чек-лист'), ('email.send', 'Отправить письмо'), ('link.attach', 'Добавить ссылку'), ('reminder.create', 'Создать напоминание')], max_length=100),
        ),
    ]
