# Generated by Django 5.2.17 on 2026-09-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_alter_actionfeature_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstage',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Пусто — используется размер по умолчанию.', null=True, verbose_name='Высота блока на графе'),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='position_x',
            field=models.FloatField(blank=True, help_text='Координата узла на холсте редактора workflow. Пусто — позиция ещё не задана вручную.', null=True, verbose_name='Позиция X на графе'),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='position_y',
            field=models.FloatField(blank=True, help_text='Координата узла на холсте редактора workflow. Пусто — позиция ещё не задана вручную.', null=True, verbose_name='Позиция Y на графе'),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Пусто — используется размер по умолчанию.', null=True, verbose_name='Ширина блока на графе'),
        ),
    ]
