# Generated by Django 5.2.17 on 2026-09-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0011_workflowstage_height_workflowstage_position_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='audience',
            field=models.CharField(choices=[('b2b', 'Организации'), ('b2c', 'Физ/юрлица')], default='b2b', max_length=10, verbose_name='Аудитория'),
        ),
    ]
