# Generated by Django 5.2.17 on 2026-09-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0012_alter_workflow_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='audience',
            field=models.CharField(choices=[('b2b', 'Организации'), ('b2c', 'Физлица')], default='b2b', max_length=10, verbose_name='Аудитория'),
        ),
    ]
