# Generated by Django 5.2.17 on 2026-09-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0013_alter_workflow_audience_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='audience',
            field=models.CharField(choices=[('b2b', 'Организации'), ('b2c', 'Физлица')], default='b2b', max_length=10, verbose_name='Целевая аудитория процесса'),
        ),
    ]
