# Generated by Django 5.2.17 on 2026-09-29

from django.db import migrations


def remove_legacy_audience_unique_constraint(apps, schema_editor):
    """Удаляет уникальность audience, ошибочно оставшуюся в старых БД."""
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT constraint_row.conname
            FROM pg_constraint AS constraint_row
            JOIN pg_class AS table_row ON table_row.oid = constraint_row.conrelid
            JOIN pg_namespace AS table_schema ON table_schema.oid = table_row.relnamespace
            JOIN pg_attribute AS column_row
              ON column_row.attrelid = table_row.oid
             AND column_row.attname = %s
            WHERE table_schema.nspname = current_schema()
              AND table_row.relname = %s
              AND constraint_row.contype = 'u'
              AND array_length(constraint_row.conkey, 1) = 1
              AND constraint_row.conkey[1] = column_row.attnum
            """,
            ["audience", "workflows_workflow"],
        )
        constraint_names = [row[0] for row in cursor.fetchall()]

        for constraint_name in constraint_names:
            cursor.execute(
                "ALTER TABLE workflows_workflow DROP CONSTRAINT "
                + schema_editor.quote_name(constraint_name),
            )


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0014_alter_workflow_audience"),
    ]

    operations = [
        migrations.RunPython(
            remove_legacy_audience_unique_constraint,
            migrations.RunPython.noop,
        ),
    ]
