# Generated by Django 5.2.17 on 2026-09-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0015_remove_legacy_workflow_audience_unique_constraint"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workflow",
            name="one_base_workflow_per_audience",
        ),
    ]
