# Generated by Django 5.2.17 on 2026-09-19 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('code', models.CharField(max_length=100, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('comment_required', models.BooleanField(default=False, verbose_name='Требует комментарий')),
                ('attachment_required', models.BooleanField(default=False, verbose_name='Требует вложение')),
            ],
            options={
                'verbose_name': 'Исход действия',
                'verbose_name_plural': 'Исходы действий',
                'ordering': ['action', 'code'],
            },
        ),
        migrations.CreateModel(
            name='B2CClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО / наименование')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('kind', models.CharField(choices=[('individual', 'Физлицо'), ('legal_entity', 'Юрлицо')], max_length=20, verbose_name='Тип клиента')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'B2C-клиент',
                'verbose_name_plural': 'B2C-клиенты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ITDirection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название направления')),
                ('external_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Внешний идентификатор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'ИТ-направление',
                'verbose_name_plural': 'ИТ-направления',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название вуза')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='ИНН')),
                ('external_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Внешний идентификатор')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email вуза')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон вуза')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вуз',
                'verbose_name_plural': 'Вузы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название вендора')),
                ('external_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Внешний идентификатор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вендор',
                'verbose_name_plural': 'Вендоры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('default_duration_days', models.PositiveIntegerField(blank=True, help_text='Используется и как план (planned_end = planned_start + default_duration_days), и как порог контроля зависания действия. NULL — контроль зависания не ведётся.', null=True, verbose_name='Плановая длительность, дней')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Можно пропустить без исхода')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Действие workflow',
                'verbose_name_plural': 'Действия workflow',
                'ordering': ['stage', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ActionInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name_snapshot', models.CharField(max_length=255, verbose_name='Название действия (слепок)')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='Плановое начало')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='Плановое окончание')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое начало')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое окончание')),
                ('execution_no', models.PositiveIntegerField(default=1, verbose_name='Номер исполнения')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_instances', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Экземпляр действия',
                'verbose_name_plural': 'Экземпляры действий',
                'ordering': ['stage_instance', 'planned_start'],
            },
        ),
        migrations.CreateModel(
            name='ActionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='action_attachments/%Y/%m/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
                ('action_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_attachments', to='crm.actioninstance', verbose_name='Экземпляр действия')),
            ],
            options={
                'verbose_name': 'Вложение действия',
                'verbose_name_plural': 'Вложения действий',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_name_snapshot', models.CharField(max_length=255, verbose_name='Название исхода (слепок)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('action_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='crm.actioninstance', verbose_name='Экземпляр действия')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_results', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_results', to='crm.actionoutcome', verbose_name='Исход')),
            ],
            options={
                'verbose_name': 'Результат действия',
                'verbose_name_plural': 'Результаты действий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('b2c_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='crm.b2cclient', verbose_name='B2C-клиент')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='crm.university', verbose_name='Вуз')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='Файл договора')),
                ('contract_number', models.CharField(blank=True, max_length=255, verbose_name='Номер договора')),
                ('sent_at', models.DateField(blank=True, null=True, verbose_name='Отправлен на подписание')),
                ('corrected_at', models.DateField(blank=True, null=True, verbose_name='Скорректирован перед подписанием')),
                ('signed_at', models.DateField(blank=True, null=True, verbose_name='Подписан')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='crm.contact', verbose_name='Сделка')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ITProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название программы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('it_direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='it_programs', to='crm.itdirection', verbose_name='ИТ-направление')),
            ],
            options={
                'verbose_name': 'ИТ-программа',
                'verbose_name_plural': 'ИТ-программы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ITProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('external_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Внешний идентификатор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('programs', models.ManyToManyField(blank=True, related_name='it_products', to='crm.itprogram', verbose_name='ИТ-программы')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_products', to='crm.vendor', verbose_name='Вендор')),
            ],
            options={
                'verbose_name': 'ИТ-продукт',
                'verbose_name_plural': 'ИТ-продукты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StageInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(choices=[('contact', 'Сделка целиком'), ('it_program', 'ИТ-программа'), ('it_product', 'ИТ-продукт')], default='contact', max_length=20, verbose_name='Тип контекста')),
                ('context_id', models.UUIDField(blank=True, help_text='Указывает на Contact.id, ITProgram.id или ITProduct.id — по значению context_type.', null=True, verbose_name='ID контекста')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_instances', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
            ],
            options={
                'verbose_name': 'Экземпляр этапа',
                'verbose_name_plural': 'Экземпляры этапов',
                'ordering': ['workflow_instance', 'added_at'],
            },
        ),
        migrations.AddField(
            model_name='actioninstance',
            name='stage_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_instances', to='crm.stageinstance', verbose_name='Экземпляр этапа'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keycloak_id', models.UUIDField(db_index=True, unique=True, verbose_name='Идентификатор в Keycloak')),
                ('last_synced_at', models.DateTimeField(auto_now=True, verbose_name='Последняя синхронизация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Код')),
                ('audience', models.CharField(choices=[('b2b', 'Вузы'), ('b2c', 'Физ/юрлица')], default='b2b', max_length=10, verbose_name='Аудитория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('stale_threshold_days', models.PositiveIntegerField(blank=True, help_text='Считается от WorkflowInstance.started_at — сколько существует вся заявка. NULL — контроль зависания заявки целиком не ведётся.', null=True, verbose_name='SLA по заявке целиком, дней')),
                ('is_base', models.BooleanField(default=False, verbose_name='Базовый workflow')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflow',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActionTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transition', to='crm.actionoutcome', verbose_name='Исход')),
                ('target_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_transitions', to='crm.workflowaction', verbose_name='Целевое действие')),
            ],
            options={
                'verbose_name': 'Переход действия',
                'verbose_name_plural': 'Переходы действий',
                'ordering': ['outcome'],
            },
        ),
        migrations.AddField(
            model_name='actionoutcome',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_outcomes', to='crm.workflowaction', verbose_name='Действие'),
        ),
        migrations.AddField(
            model_name='actioninstance',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_instances', to='crm.workflowaction', verbose_name='Действие'),
        ),
        migrations.CreateModel(
            name='ActionDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_dependencies_as_action', to='crm.workflowaction', verbose_name='Действие')),
                ('depends_on_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_dependencies_as_depends_on_action', to='crm.workflowaction', verbose_name='Зависит от действия')),
            ],
            options={
                'verbose_name': 'Зависимость действия',
                'verbose_name_plural': 'Зависимости действий',
                'ordering': ['action', 'depends_on_action'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=50, verbose_name='Тип изменения')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Тип сущности')),
                ('entity_id', models.UUIDField(verbose_name='ID сущности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_changes', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_changes', to='crm.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Изменение workflow',
                'verbose_name_plural': 'Изменения workflow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начат')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='crm.contact', verbose_name='Сделка')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_instances', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances', to='crm.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Процесс workflow',
                'verbose_name_plural': 'Процессы workflow',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='stageinstance',
            name='workflow_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_instances', to='crm.workflowinstance', verbose_name='Процесс workflow'),
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(blank=True, max_length=50, verbose_name='Тип этапа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('is_initial', models.BooleanField(default=False, verbose_name='Начальный этап')),
                ('is_final', models.BooleanField(default=False, verbose_name='Финальный этап')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Можно пропустить')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_stages', to='crm.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Этап workflow',
                'verbose_name_plural': 'Этапы workflow',
                'ordering': ['workflow', 'sort_order'],
            },
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_actions', to='crm.workflowstage', verbose_name='Этап'),
        ),
        migrations.AddField(
            model_name='stageinstance',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_instances', to='crm.workflowstage', verbose_name='Этап'),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('signed_at', models.DateField(blank=True, null=True, verbose_name='Дата подписания лицензии')),
                ('superseded_at', models.DateTimeField(blank=True, null=True, verbose_name='Заменена')),
                ('valid_until_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Действует до (год)')),
                ('is_signed', models.BooleanField(default=False, verbose_name='Подписана')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующая')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='crm.contract', verbose_name='Договор')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('it_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='crm.itproduct', verbose_name='ИТ-продукт')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('contract', 'it_product'), name='one_active_license_per_contract_product')],
            },
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Назначен')),
                ('unassigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Снят с назначения')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsibles_as_assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='crm.contact', verbose_name='Сделка')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsibles_as_manager', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
            ],
            options={
                'verbose_name': 'Ответственный',
                'verbose_name_plural': 'Ответственные',
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('unassigned_at__isnull', True)), fields=('contact',), name='one_active_responsible_per_contact')],
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('b2c_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='crm.b2cclient', verbose_name='B2C-клиент')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='crm.university', verbose_name='Вуз')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
                'ordering': ['full_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('b2c_client__isnull', True), ('university__isnull', False)), models.Q(('b2c_client__isnull', False), ('university__isnull', True)), _connector='OR'), name='contact_person_exactly_one_counterparty'), models.UniqueConstraint(fields=('university', 'full_name'), name='unique_university_contact_name'), models.UniqueConstraint(fields=('b2c_client', 'full_name'), name='unique_b2c_client_contact_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('b2c_client__isnull', True), ('university__isnull', False)), models.Q(('b2c_client__isnull', False), ('university__isnull', True)), _connector='OR'), name='contact_exactly_one_counterparty'),
        ),
        migrations.AddConstraint(
            model_name='itproduct',
            constraint=models.UniqueConstraint(fields=('vendor', 'name'), name='unique_product_per_vendor'),
        ),
        migrations.AddConstraint(
            model_name='itproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('vendor__isnull', True)), fields=('name',), name='unique_product_without_vendor'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_base', True)), fields=('audience',), name='one_base_workflow_per_audience'),
        ),
        migrations.AddConstraint(
            model_name='actionoutcome',
            constraint=models.UniqueConstraint(fields=('action', 'code'), name='unique_action_outcome_code'),
        ),
        migrations.AddConstraint(
            model_name='actiondependency',
            constraint=models.UniqueConstraint(fields=('action', 'depends_on_action'), name='unique_action_dependency'),
        ),
        migrations.AddConstraint(
            model_name='actiondependency',
            constraint=models.CheckConstraint(condition=models.Q(('action', models.F('depends_on_action')), _negated=True), name='action_dependency_no_self_reference'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(fields=('workflow', 'sort_order'), name='unique_workflow_stage_order'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_initial', True)), fields=('workflow',), name='one_initial_stage_per_workflow'),
        ),
        migrations.AddConstraint(
            model_name='workflowaction',
            constraint=models.UniqueConstraint(fields=('stage', 'sort_order'), name='unique_stage_action_order'),
        ),
    ]
