# Generated by Django 5.2.17 on 2026-09-27 20:54

import django.db.models.deletion
import sova.core.fields
import sova.core.files
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0010_remove_other_contact_channel'),
        ('interactions', '0016_interaction_sequence_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('email', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Email')),
                ('email_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('phone', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Телефон')),
                ('phone_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('consent_at', models.DateTimeField(blank=True, null=True, verbose_name='Согласие на обработку ПД')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Обучающийся',
                'verbose_name_plural': 'Обучающиеся',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='LearnerPersonalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол')),
                ('birth_date', sova.core.fields.EncryptedDateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('last_name_dative', models.CharField(blank=True, max_length=255, verbose_name='Фамилия (дательный падеж)')),
                ('first_name_dative', models.CharField(blank=True, max_length=255, verbose_name='Имя (дательный падеж)')),
                ('middle_name_dative', models.CharField(blank=True, max_length=255, verbose_name='Отчество (дательный падеж)')),
                ('snils', sova.core.fields.EncryptedTextField(blank=True, verbose_name='СНИЛС')),
                ('snils_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('passport_series', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Серия паспорта')),
                ('passport_number', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Номер паспорта')),
                ('passport_issued_by', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Кем выдан паспорт')),
                ('passport_issued_at', sova.core.fields.EncryptedDateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('passport_division_code', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Код подразделения')),
                ('registration_region', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Регион регистрации')),
                ('registration_locality', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Населённый пункт регистрации')),
                ('registration_street', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Улица регистрации')),
                ('registration_house', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Дом регистрации')),
                ('registration_apartment', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Квартира регистрации')),
                ('registration_postcode', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Индекс регистрации')),
                ('education_level', models.CharField(blank=True, choices=[('none', 'Без образования'), ('basic_general', 'Основное общее образование - 9 классов'), ('secondary_general', 'Среднее общее образование - 11 классов'), ('secondary_vocational', 'Среднее профессиональное образование'), ('bachelor', 'Высшее образование – бакалавриат'), ('specialist_master', 'Высшее образование – специалитет, магистратура'), ('higher_qualification', 'Высшее образование – подготовка кадров высшей квалификации')], max_length=30, verbose_name='Образование')),
                ('diploma_qualification', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Профессия по диплому')),
                ('diploma_institution', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Учебное заведение по диплому')),
                ('diploma_last_name', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Фамилия, указанная в дипломе')),
                ('diploma_series', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Серия диплома')),
                ('diploma_number', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Номер диплома')),
                ('diploma_registration_number', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Регистрационный номер диплома')),
                ('diploma_issued_at', sova.core.fields.EncryptedDateField(blank=True, null=True, verbose_name='Дата выдачи диплома')),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_data', to='training.learner', verbose_name='Обучающийся')),
            ],
            options={
                'verbose_name': 'Персональные данные обучающегося',
                'verbose_name_plural': 'Персональные данные обучающихся',
            },
        ),
        migrations.CreateModel(
            name='LearnerPersonalDataAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('fields', models.JSONField(default=list, verbose_name='Поля')),
                ('action', models.CharField(choices=[('read', 'Просмотр'), ('export', 'Выгрузка')], default='read', max_length=10, verbose_name='Действие')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('learner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_data_access_log', to='training.learner', verbose_name='Обучающийся')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ к персональным данным',
                'verbose_name_plural': 'Журнал доступа к персональным данным',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Заявка на обучение',
                'verbose_name_plural': 'Заявки на обучение',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingApplicationLearner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='training.trainingapplication', verbose_name='Заявка')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='training.learner', verbose_name='Обучающийся')),
            ],
            options={
                'verbose_name': 'Участник заявки',
                'verbose_name_plural': 'Участники заявок',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='learners',
            field=models.ManyToManyField(blank=True, related_name='applications', through='training.TrainingApplicationLearner', to='training.learner', verbose_name='Обучающиеся'),
        ),
        migrations.CreateModel(
            name='TrainingInstructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=64, verbose_name='Telegram')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Подразделение')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('academic_degree', models.CharField(choices=[('none', 'Нет'), ('candidate', 'Кандидат наук'), ('doctor', 'Доктор наук')], default='none', max_length=20, verbose_name='Учёная степень')),
                ('academic_title', models.CharField(choices=[('none', 'Нет'), ('docent', 'Доцент'), ('professor', 'Профессор')], default='none', max_length=20, verbose_name='Учёное звание')),
                ('teaching_experience_years', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Стаж преподавания, лет')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('lms_external_id', models.CharField(blank=True, max_length=255, verbose_name='ID в LMS')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('b2c_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_instructors', to='catalog.b2cclient', verbose_name='B2C-клиент')),
                ('directions', models.ManyToManyField(blank=True, related_name='training_instructors', to='catalog.direction', verbose_name='Направления')),
                ('programs', models.ManyToManyField(blank=True, related_name='training_instructors', to='catalog.program', verbose_name='Программы')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_instructors', to='catalog.university', verbose_name='Вуз')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingInstructorQualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('kind', models.CharField(choices=[('initial', 'Обучение преподавателей'), ('advanced', 'Повышение квалификации')], max_length=20, verbose_name='Вид подготовки')),
                ('completed_at', models.DateField(verbose_name='Дата завершения')),
                ('document_type', models.CharField(blank=True, choices=[('certificate', 'Сертификат'), ('diploma', 'Удостоверение'), ('other', 'Другое')], max_length=20, verbose_name='Тип документа')),
                ('document_number', models.CharField(blank=True, max_length=255, verbose_name='Номер документа')),
                ('document_file', models.FileField(blank=True, max_length=500, null=True, upload_to=sova.core.files.uuid_upload_to('training/qualifications'), verbose_name='Файл документа')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='training.traininginstructor', verbose_name='Преподаватель')),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_instructor_qualifications', to='interactions.interaction', verbose_name='Взаимодействие')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_instructor_qualifications', to='catalog.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Подготовка преподавателя',
                'verbose_name_plural': 'Подготовка преподавателей',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingStream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('starts_at', models.DateField(blank=True, null=True, verbose_name='Начало обучения')),
                ('ends_at', models.DateField(blank=True, null=True, verbose_name='Окончание обучения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('enrollment_open', 'Идёт набор'), ('in_progress', 'Идёт обучение'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('interaction_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streams', to='interactions.interactionprogram', verbose_name='Программа взаимодействия')),
            ],
            options={
                'verbose_name': 'Поток обучения',
                'verbose_name_plural': 'Потоки обучения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='trainingapplication',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='training.trainingstream', verbose_name='Поток'),
        ),
        migrations.CreateModel(
            name='TrainingStreamInstructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто назначил')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stream_links', to='training.traininginstructor', verbose_name='Преподаватель')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_links', to='training.trainingstream', verbose_name='Поток')),
            ],
            options={
                'verbose_name': 'Преподаватель потока',
                'verbose_name_plural': 'Преподаватели потоков',
            },
        ),
        migrations.AddField(
            model_name='trainingstream',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='streams', through='training.TrainingStreamInstructor', to='training.traininginstructor', verbose_name='Преподаватели'),
        ),
        migrations.AddConstraint(
            model_name='trainingapplicationlearner',
            constraint=models.UniqueConstraint(fields=('application', 'learner'), name='unique_training_application_learner'),
        ),
        migrations.AddConstraint(
            model_name='traininginstructor',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('b2c_client__isnull', True), ('university__isnull', False)), models.Q(('b2c_client__isnull', False), ('university__isnull', True)), _connector='OR'), name='training_instructor_exactly_one_organization'),
        ),
        migrations.AddConstraint(
            model_name='traininginstructor',
            constraint=models.UniqueConstraint(condition=models.Q(('lms_external_id', ''), _negated=True), fields=('lms_external_id',), name='unique_training_instructor_lms_id'),
        ),
        migrations.AddConstraint(
            model_name='trainingstreaminstructor',
            constraint=models.UniqueConstraint(fields=('stream', 'instructor'), name='unique_training_stream_instructor'),
        ),
        migrations.AddConstraint(
            model_name='trainingstream',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='training_stream_dates_order'),
        ),
    ]
