# Generated by Django 5.2.17 on 2026-09-28 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_b2cclient_kind_and_more'),
        ('training', '0002_rename_university_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininginstructor',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_instructors', to='catalog.organization', verbose_name='Организация'),
        ),
    ]
