# Generated by Django 5.2.17 on 2026-09-29 06:53

import sova.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_traininginstructor_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininginstructor',
            name='phone',
            field=models.CharField(blank=True, max_length=50, validators=[sova.core.validators.validate_phone], verbose_name='Телефон'),
        ),
    ]
