# Generated by Django 5.2.17 on 2026-09-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_phone_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerpersonaldataaccesslog',
            name='action',
            field=models.CharField(choices=[('read', 'Просмотр'), ('export', 'Выгрузка'), ('update', 'Изменение')], default='read', max_length=10, verbose_name='Действие'),
        ),
    ]
