# Generated by Django 5.2.17 on 2026-09-20 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B2CClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО / наименование')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('kind', models.CharField(choices=[('individual', 'Физлицо'), ('legal_entity', 'Юрлицо')], max_length=20, verbose_name='Тип клиента')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'B2C-клиент',
                'verbose_name_plural': 'B2C-клиенты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ITDirection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название направления')),
                ('external_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Внешний идентификатор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'ИТ-направление',
                'verbose_name_plural': 'ИТ-направления',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название вуза')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='ИНН')),
                ('external_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Внешний идентификатор')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email вуза')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон вуза')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вуз',
                'verbose_name_plural': 'Вузы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название вендора')),
                ('external_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Внешний идентификатор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вендор',
                'verbose_name_plural': 'Вендоры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ITProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название программы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('it_direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='it_programs', to='catalog.itdirection', verbose_name='ИТ-направление')),
            ],
            options={
                'verbose_name': 'ИТ-программа',
                'verbose_name_plural': 'ИТ-программы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('b2c_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='catalog.b2cclient', verbose_name='B2C-клиент')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='catalog.university', verbose_name='Вуз')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
                'ordering': ['full_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('b2c_client__isnull', True), ('university__isnull', False)), models.Q(('b2c_client__isnull', False), ('university__isnull', True)), _connector='OR'), name='contact_person_exactly_one_counterparty'), models.UniqueConstraint(fields=('university', 'full_name'), name='unique_university_contact_name'), models.UniqueConstraint(fields=('b2c_client', 'full_name'), name='unique_b2c_client_contact_name')],
            },
        ),
        migrations.CreateModel(
            name='ITProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('external_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Внешний идентификатор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('programs', models.ManyToManyField(blank=True, related_name='it_products', to='catalog.itprogram', verbose_name='ИТ-программы')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_products', to='catalog.vendor', verbose_name='Вендор')),
            ],
            options={
                'verbose_name': 'ИТ-продукт',
                'verbose_name_plural': 'ИТ-продукты',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'name'), name='unique_product_per_vendor'), models.UniqueConstraint(condition=models.Q(('vendor__isnull', True)), fields=('name',), name='unique_product_without_vendor')],
            },
        ),
    ]
