# Generated by Django 5.2.17 on 2026-09-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='cited_by_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество цитирований'),
        ),
        migrations.AddField(
            model_name='university',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='university',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2, verbose_name='Код страны (ISO 3166-1 alpha-2)'),
        ),
        migrations.AddField(
            model_name='university',
            name='homepage_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='university',
            name='institution_type',
            field=models.CharField(choices=[('education', 'Образование'), ('healthcare', 'Здравоохранение'), ('company', 'Компания'), ('archive', 'Архив'), ('nonprofit', 'Некоммерческая организация'), ('government', 'Государственная организация'), ('facility', 'Научный объект'), ('funder', 'Фонд'), ('other', 'Другое')], default='education', max_length=20, verbose_name='Тип организации'),
        ),
        migrations.AddField(
            model_name='university',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='university',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='university',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название на английском'),
        ),
        migrations.AddField(
            model_name='university',
            name='region',
            field=models.CharField(blank=True, max_length=255, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='university',
            name='works_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество публикаций'),
        ),
    ]
