# Generated by Django 5.2.17 on 2026-09-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_university_cited_by_count_university_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое название'),
        ),
    ]
