# Generated by Django 5.2.17 on 2026-09-20 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_it_direction_it_product_it_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.program', verbose_name='ИТ-программы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.vendor', verbose_name='Вендор'),
        ),
        migrations.AlterField(
            model_name='program',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='catalog.direction', verbose_name='ИТ-направление'),
        ),
    ]
