# Generated by Django 5.2.17 on 2026-09-22 17:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_direction_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogImportMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('catalog_type', models.CharField(choices=[('university', 'Вузы'), ('vendor', 'Вендоры'), ('direction', 'Направления'), ('program', 'Программы'), ('product', 'Продукты'), ('contact_person', 'Ответственные от вуза'), ('contract_registry', 'Реестр договоров')], max_length=32, verbose_name='Тип каталога')),
                ('source_column', models.CharField(max_length=255, verbose_name='Колонка в файле')),
                ('target_field', models.CharField(max_length=64, verbose_name='Каноническое поле')),
            ],
            options={
                'verbose_name': 'Маппинг импорта каталога',
                'verbose_name_plural': 'Маппинги импорта каталогов',
                'ordering': ['catalog_type', 'target_field'],
                'constraints': [models.UniqueConstraint(fields=('catalog_type', 'source_column'), name='unique_mapping_source_column'), models.UniqueConstraint(fields=('catalog_type', 'target_field'), name='unique_mapping_target_field')],
            },
        ),
    ]
