# Generated by Django 5.2.17 on 2026-09-22 20:26

from collections import defaultdict

import django.db.models.functions.text
from django.db import migrations, models

from sova.core.text import normalize_text

# Текстовые поля, которые модели теперь нормализуют при сохранении (NormalizedTextFieldsMixin).
NORMALIZED_FIELDS = {
    "University": ("name", "name_en", "short_name", "external_code"),
    "Vendor": ("name", "external_code"),
    "Direction": ("name", "external_code"),
    "Program": ("name",),
    "Product": ("name", "external_code"),
    "ContactPerson": ("full_name", "position", "phone"),
}

# Новые ограничения уникальности без учёта регистра: (поля ключа, FK-поля, при пустом значении которых
# ограничение не действует). Последнее поле ключа — текстовое, сравнивается в нижнем регистре.
UNIQUE_KEYS = {
    "University": ((("name",), ()), (("external_code",), ())),
    "Vendor": ((("name",), ()), (("external_code",), ())),
    "Direction": ((("name",), ()), (("external_code",), ())),
    # vendor_id=None — продукты без вендора: для них отдельное ограничение, в ключе это та же группа.
    "Product": ((("vendor_id", "name"), ()), (("external_code",), ())),
    "ContactPerson": (
        (("university_id", "full_name"), ("university_id",)),
        (("b2c_client_id", "full_name"), ("b2c_client_id",)),
    ),
}


def normalize_existing_values(apps, schema_editor) -> None:
    """
    Нормализует уже сохранённые значения и проверяет, что новые ограничения без учёта регистра выполнимы.

    Конфликты (две записи, совпадающие после нормализации и без учёта регистра) не сливаются
    автоматически: миграция останавливается со списком, записи нужно исправить вручную. Проверка идёт
    до записи — иначе сохранение упёрлось бы в ещё действующие старые ограничения.
    """
    updates = []
    conflicts = []
    for model_name, fields in NORMALIZED_FIELDS.items():
        model = apps.get_model("catalog", model_name)
        objects = list(model.objects.all())

        normalized = {}
        for obj in objects:
            values = {}
            for field in fields:
                value = getattr(obj, field)
                values[field] = normalize_text(value) if isinstance(value, str) else value
            normalized[obj.pk] = values
            changed = [field for field in fields if values[field] != getattr(obj, field)]
            if changed:
                updates.append((obj, values, changed))

        for key_fields, required_fields in UNIQUE_KEYS.get(model_name, ()):
            *fk_fields, text_field = key_fields
            groups = defaultdict(list)
            for obj in objects:
                if any(getattr(obj, field) is None for field in required_fields):
                    continue
                text_value = normalized[obj.pk][text_field]
                if text_value is None:
                    continue
                key = (*(getattr(obj, field) for field in fk_fields), text_value.lower())
                groups[key].append(obj)
            for key, duplicates in groups.items():
                if len(duplicates) > 1:
                    listed = ", ".join(f"«{getattr(obj, text_field)}» (id {obj.pk})" for obj in duplicates)
                    conflicts.append(f"  {model._meta.verbose_name}, {text_field} «{key[-1]}»: {listed}")

    if conflicts:
        raise RuntimeError(
            "Записи совпадают после нормализации текста и без учёта регистра — исправьте их вручную "
            "и повторите миграцию:\n" + "\n".join(conflicts)
        )

    for obj, values, changed in updates:
        for field in changed:
            setattr(obj, field, values[field])
        obj.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_catalogimportmapping'),
    ]

    operations = [
        migrations.RunPython(normalize_existing_values, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='contactperson',
            name='unique_university_contact_name',
        ),
        migrations.RemoveConstraint(
            model_name='contactperson',
            name='unique_b2c_client_contact_name',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_per_vendor',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_without_vendor',
        ),
        migrations.AlterField(
            model_name='direction',
            name='external_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Внешний идентификатор'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название направления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Внешний идентификатор'),
        ),
        migrations.AlterField(
            model_name='university',
            name='external_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Внешний идентификатор'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название вуза'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='external_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Внешний идентификатор'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название вендора'),
        ),
        migrations.AddConstraint(
            model_name='contactperson',
            constraint=models.UniqueConstraint(models.F('university'), django.db.models.functions.text.Lower('full_name'), name='unique_university_contact_name', violation_error_message='Контактное лицо с таким ФИО у этого вуза уже существует.'),
        ),
        migrations.AddConstraint(
            model_name='contactperson',
            constraint=models.UniqueConstraint(models.F('b2c_client'), django.db.models.functions.text.Lower('full_name'), name='unique_b2c_client_contact_name', violation_error_message='Контактное лицо с таким ФИО у этого B2C-клиента уже существует.'),
        ),
        migrations.AddConstraint(
            model_name='direction',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_direction_name_ci', violation_error_message='Направление с таким названием уже существует.'),
        ),
        migrations.AddConstraint(
            model_name='direction',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('external_code'), name='unique_direction_external_code_ci', violation_error_message='Направление с таким внешним идентификатором уже существует.'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(models.F('vendor'), django.db.models.functions.text.Lower('name'), name='unique_product_per_vendor', violation_error_message='Продукт с таким названием у этого вендора уже существует.'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('vendor__isnull', True)), name='unique_product_without_vendor', violation_error_message='Продукт с таким названием без вендора уже существует.'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('external_code'), name='unique_product_external_code_ci', violation_error_message='Продукт с таким внешним идентификатором уже существует.'),
        ),
        migrations.AddConstraint(
            model_name='university',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_university_name_ci', violation_error_message='Вуз с таким названием уже существует.'),
        ),
        migrations.AddConstraint(
            model_name='university',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('external_code'), name='unique_university_external_code_ci', violation_error_message='Вуз с таким внешним идентификатором уже существует.'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_vendor_name_ci', violation_error_message='Вендор с таким названием уже существует.'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('external_code'), name='unique_vendor_external_code_ci', violation_error_message='Вендор с таким внешним идентификатором уже существует.'),
        ),
    ]
