# Generated by Django 5.2.17 on 2026-09-26 21:38

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_case_insensitive_uniqueness'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2CClientContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('preferred_channels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('email', 'Почта'), ('telegram', 'Чат в Telegram'), ('phone', 'Телефон'), ('other', 'Другое')], max_length=20), blank=True, default=list, size=None, verbose_name='Способы связи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('started_at', models.DateField(default=django.utils.timezone.localdate, help_text='С какой даты человек работает с организацией в этом периоде', verbose_name='Дата начала')),
                ('ended_at', models.DateField(blank=True, help_text='Когда человек перестал работать с организацией (уволился, сменил роль). Только у неактивной связи', null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Связь с B2C-клиентом',
                'verbose_name_plural': 'Связи с B2C-клиентами',
                'ordering': ['contact__full_name', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UniversityContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('preferred_channels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('email', 'Почта'), ('telegram', 'Чат в Telegram'), ('phone', 'Телефон'), ('other', 'Другое')], max_length=20), blank=True, default=list, size=None, verbose_name='Способы связи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('started_at', models.DateField(default=django.utils.timezone.localdate, help_text='С какой даты человек работает с организацией в этом периоде', verbose_name='Дата начала')),
                ('ended_at', models.DateField(blank=True, help_text='Когда человек перестал работать с организацией (уволился, сменил роль). Только у неактивной связи', null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Связь с вузом',
                'verbose_name_plural': 'Связи с вузами',
                'ordering': ['contact__full_name', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('preferred_channels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('email', 'Почта'), ('telegram', 'Чат в Telegram'), ('phone', 'Телефон'), ('other', 'Другое')], max_length=20), blank=True, default=list, size=None, verbose_name='Способы связи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('started_at', models.DateField(default=django.utils.timezone.localdate, help_text='С какой даты человек работает с организацией в этом периоде', verbose_name='Дата начала')),
                ('ended_at', models.DateField(blank=True, help_text='Когда человек перестал работать с организацией (уволился, сменил роль). Только у неактивной связи', null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Связь с вендором',
                'verbose_name_plural': 'Связи с вендорами',
                'ordering': ['contact__full_name', '-started_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='contactperson',
            name='contact_person_exactly_one_counterparty',
        ),
        migrations.RemoveConstraint(
            model_name='contactperson',
            name='unique_university_contact_name',
        ),
        migrations.RemoveConstraint(
            model_name='contactperson',
            name='unique_b2c_client_contact_name',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='b2c_client',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='position',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='university',
        ),
        migrations.AddField(
            model_name='contactperson',
            name='telegram',
            field=models.CharField(blank=True, help_text='Ник без @', max_length=64, verbose_name='Telegram'),
        ),
        migrations.AddIndex(
            model_name='contactperson',
            index=models.Index(django.db.models.functions.text.Lower('full_name'), name='contact_person_full_name_ci'),
        ),
        migrations.AddIndex(
            model_name='contactperson',
            index=models.Index(django.db.models.functions.text.Lower('email'), name='contact_person_email_ci'),
        ),
        migrations.AddIndex(
            model_name='contactperson',
            index=models.Index(django.db.models.functions.text.Lower('telegram'), name='contact_person_telegram_ci'),
        ),
        migrations.AddField(
            model_name='b2cclientcontact',
            name='b2c_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='catalog.b2cclient', verbose_name='B2C-клиент'),
        ),
        migrations.AddField(
            model_name='b2cclientcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b2c_client_links', to='catalog.contactperson', verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='universitycontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='university_links', to='catalog.contactperson', verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='universitycontact',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='catalog.university', verbose_name='Вуз'),
        ),
        migrations.AddField(
            model_name='vendorcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_links', to='catalog.contactperson', verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='vendorcontact',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='vendor_contacts', to='catalog.product', verbose_name='Продукты'),
        ),
        migrations.AddField(
            model_name='vendorcontact',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='catalog.vendor', verbose_name='Вендор'),
        ),
        migrations.AddConstraint(
            model_name='b2cclientcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('contact', 'b2c_client'), name='unique_active_b2c_client_contact', violation_error_message='Это контактное лицо уже работает с этой организацией: закройте текущий период.'),
        ),
        migrations.AddConstraint(
            model_name='b2cclientcontact',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='b2c_client_contact_ended_after_started', violation_error_message='Дата окончания раньше даты начала.'),
        ),
        migrations.AddConstraint(
            model_name='universitycontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('contact', 'university'), name='unique_active_university_contact', violation_error_message='Это контактное лицо уже работает с этой организацией: закройте текущий период.'),
        ),
        migrations.AddConstraint(
            model_name='universitycontact',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='university_contact_ended_after_started', violation_error_message='Дата окончания раньше даты начала.'),
        ),
        migrations.AddConstraint(
            model_name='vendorcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('contact', 'vendor'), name='unique_active_vendor_contact', violation_error_message='Это контактное лицо уже работает с этой организацией: закройте текущий период.'),
        ),
        migrations.AddConstraint(
            model_name='vendorcontact',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='vendor_contact_ended_after_started', violation_error_message='Дата окончания раньше даты начала.'),
        ),
    ]
