# Generated by Django 5.2.17 on 2026-09-27 10:17

import django.contrib.postgres.fields
from django.db import migrations, models
from django.db.models import Func, Value

AFFILIATION_MODELS = ("UniversityContact", "B2CClientContact", "VendorContact")


def remove_other_channel(apps, schema_editor):
    """Убирает способ связи «Другое» из уже сохранённых связей: остаются почта, Telegram и телефон."""
    for model_name in AFFILIATION_MODELS:
        model = apps.get_model("catalog", model_name)
        model.objects.filter(preferred_channels__contains=["other"]).update(
            preferred_channels=Func("preferred_channels", Value("other"), function="array_remove")
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_affiliation_periods'),
    ]

    operations = [
        migrations.RunPython(remove_other_channel, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='b2cclientcontact',
            name='preferred_channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('email', 'Почта'), ('telegram', 'Чат в Telegram'), ('phone', 'Телефон')], max_length=20), blank=True, default=list, size=None, verbose_name='Способы связи'),
        ),
        migrations.AlterField(
            model_name='universitycontact',
            name='preferred_channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('email', 'Почта'), ('telegram', 'Чат в Telegram'), ('phone', 'Телефон')], max_length=20), blank=True, default=list, size=None, verbose_name='Способы связи'),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='preferred_channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('email', 'Почта'), ('telegram', 'Чат в Telegram'), ('phone', 'Телефон')], max_length=20), blank=True, default=list, size=None, verbose_name='Способы связи'),
        ),
    ]
