# Generated by Django 5.2.17 on 2026-09-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_other_contact_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimportmapping',
            name='catalog_type',
            field=models.CharField(choices=[('university', 'Вузы'), ('vendor', 'Вендоры'), ('direction', 'Направления'), ('program', 'Программы'), ('product', 'Продукты'), ('contact_person', 'Ответственные от вуза'), ('contract_registry', 'Реестр договоров'), ('learner', 'Обучающиеся')], max_length=32, verbose_name='Тип каталога'),
        ),
    ]
