# Generated by Django 5.2.17 on 2026-09-28 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_organization_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='organizationcontact',
            options={'ordering': ['contact__full_name'], 'verbose_name': 'Связь с организацией', 'verbose_name_plural': 'Связи с организациями'},
        ),
        migrations.RemoveField(
            model_name='b2cclient',
            name='kind',
        ),
        migrations.AlterField(
            model_name='b2cclient',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='catalogimportmapping',
            name='catalog_type',
            field=models.CharField(choices=[('organization', 'Организации'), ('vendor', 'Вендоры'), ('direction', 'Направления'), ('program', 'Программы'), ('product', 'Продукты'), ('contact_person', 'Ответственные от организации'), ('contract_registry', 'Реестр договоров'), ('learner', 'Обучающиеся')], max_length=32, verbose_name='Тип каталога'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон организации'),
        ),
        migrations.AlterField(
            model_name='organizationcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_links', to='catalog.contactperson', verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='organizationcontact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='catalog.organization', verbose_name='Организация'),
        ),
    ]
