# Generated by Django 5.2.17 on 2026-09-28 12:22

import django.db.models.deletion
import sova.core.fields
import uuid
from django.conf import settings
from django.db import migrations, models


GEO_FIELDS = ("country_code", "region", "city", "lat", "lon")


def move_geo_to_actual_address(apps, schema_editor) -> None:
    """География организации (из ROR — местоположение кампуса) становится её фактическим адресом."""
    organization_model = apps.get_model("catalog", "Organization")
    address_model = apps.get_model("catalog", "OrganizationAddress")
    addresses = []
    for organization in organization_model.objects.all().only("pk", *GEO_FIELDS):
        values = {field: getattr(organization, field) for field in GEO_FIELDS}
        if not any(value not in ("", None) for value in values.values()):
            continue
        addresses.append(address_model(organization_id=organization.pk, kind="actual", **values))
    address_model.objects.bulk_create(addresses, batch_size=500)


def move_geo_back(apps, schema_editor) -> None:
    """Откат: география возвращается в организацию из фактического адреса, а если его нет — из юридического."""
    organization_model = apps.get_model("catalog", "Organization")
    address_model = apps.get_model("catalog", "OrganizationAddress")
    for address in address_model.objects.order_by("kind"):  # «actual» раньше «legal» — фактический в приоритете
        organization_model.objects.filter(pk=address.organization_id, city="", lat=None).update(
            **{field: getattr(address, field) for field in GEO_FIELDS}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_b2cclient_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='actual_same_as_legal',
            field=models.BooleanField(default=False, help_text='Фактический адрес не хранится отдельно — берётся юридический.', verbose_name='Фактический адрес совпадает с юридическим'),
        ),
        migrations.CreateModel(
            name='B2CClientAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='Код страны (ISO 3166-1 alpha-2)')),
                ('region', models.CharField(blank=True, max_length=255, verbose_name='Регион')),
                ('city', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Город / населённый пункт')),
                ('street', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Улица')),
                ('house', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Дом, корпус, строение')),
                ('apartment', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Квартира')),
                ('postal_code', sova.core.fields.EncryptedTextField(blank=True, verbose_name='Индекс')),
                ('b2c_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='catalog.b2cclient', verbose_name='B2C-клиент')),
            ],
            options={
                'verbose_name': 'Адрес B2C-клиента',
                'verbose_name_plural': 'Адреса B2C-клиентов',
            },
        ),
        migrations.CreateModel(
            name='B2CClientAddressAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('fields', models.JSONField(default=list, verbose_name='Поля')),
                ('action', models.CharField(choices=[('read', 'Просмотр'), ('update', 'Изменение')], default='read', max_length=10, verbose_name='Действие')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('b2c_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_access_log', to='catalog.b2cclient', verbose_name='B2C-клиент')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ к адресу B2C-клиента',
                'verbose_name_plural': 'Журнал доступа к адресам B2C-клиентов',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='Код страны (ISO 3166-1 alpha-2)')),
                ('region', models.CharField(blank=True, max_length=255, verbose_name='Регион')),
                ('city', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Город / населённый пункт')),
                ('kind', models.CharField(choices=[('legal', 'Юридический'), ('actual', 'Фактический')], max_length=10, verbose_name='Тип адреса')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=50, verbose_name='Дом, корпус, строение')),
                ('office', models.CharField(blank=True, max_length=50, verbose_name='Офис / помещение')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Индекс')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='catalog.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Адрес организации',
                'verbose_name_plural': 'Адреса организаций',
                'ordering': ['organization', 'kind'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'kind'), name='unique_organization_address_kind', violation_error_message='У организации уже есть адрес этого типа.'), models.CheckConstraint(condition=models.Q(models.Q(('lat__isnull', True), ('lon__isnull', True)), models.Q(('lat__isnull', False), ('lon__isnull', False)), _connector='OR'), name='organization_address_coordinates_pair', violation_error_message='Широта и долгота указываются вместе.'), models.CheckConstraint(condition=models.Q(('lat__isnull', True), models.Q(('lat__gte', -90), ('lat__lte', 90)), _connector='OR'), name='organization_address_lat_range', violation_error_message='Широта — от −90 до 90.'), models.CheckConstraint(condition=models.Q(('lon__isnull', True), models.Q(('lon__gte', -180), ('lon__lte', 180)), _connector='OR'), name='organization_address_lon_range', violation_error_message='Долгота — от −180 до 180.')],
            },
        ),
        migrations.RunPython(move_geo_to_actual_address, move_geo_back),
        migrations.RemoveField(
            model_name='organization',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='region',
        ),
    ]
