# Generated by Django 5.2.17 on 2026-09-29 06:53

import sova.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2cclient',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[sova.core.validators.validate_inn], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='b2cclient',
            name='phone',
            field=models.CharField(blank=True, max_length=50, validators=[sova.core.validators.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='phone',
            field=models.CharField(blank=True, max_length=50, validators=[sova.core.validators.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[sova.core.validators.validate_inn], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=50, validators=[sova.core.validators.validate_phone], verbose_name='Телефон организации'),
        ),
    ]
