# Generated by Django 5.2.17 on 2026-09-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_inn_phone_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('education', 'Образование'), ('healthcare', 'Здравоохранение'), ('company', 'Компания'), ('nonprofit', 'Некоммерческая организация'), ('government', 'Государственная организация'), ('facility', 'Научный объект'), ('funder', 'Фонд')], default='education', max_length=20, verbose_name='Тип организации'),
        ),
    ]
